# Generated by Django 6.0.2 on 2026-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Pendiente', '🟡 Pendiente'), ('Aprobada', '🟢 Aprobada'), ('Rechazada', '🔴 Rechazada'), ('Modificada', '🟠 Modificada'), ('Recepcionada', '✅ Recepcionada')], default='Pendiente', max_length=20),
        ),
    ]
