# Generated by Django 6.0.2 on 2026-02-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_solicitud_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaBaseDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_db', models.CharField(max_length=100, unique=True)),
                ('campos', models.JSONField(default=list)),
            ],
        ),
    ]
