# Generated by Django 6.0.2 on 2026-02-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_plantillabasedatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='db_destino',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='db_origen',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
