# Generated by Django 6.0.2 on 2026-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_solicitud_db_destino_solicitud_db_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bodega_preferida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='db_preferida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='orden_formularios',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pagina_inicio',
            field=models.CharField(default='inventario', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tema',
            field=models.CharField(default='system', max_length=20),
        ),
    ]
