# Generated by Django 6.0.2 on 2026-02-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_usuario_bodega_preferida_usuario_db_preferida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Pendiente', '🟡 Pendiente'), ('Aprobada', '🟢 Aprobada'), ('Rechazada', '🔴 Rechazada'), ('Modificada', '🟠 Modificada'), ('Recepcionada', '✅ Recepcionada'), ('Cancelada', '⚫ Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
