# Generated by Django 6.0.2 on 2026-02-19 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_solicitud_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIntegridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_monitoreo', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_monitor', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('equipo', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('estatus', models.CharField(blank=True, choices=[('C', 'C'), ('NC', 'NC')], max_length=2, null=True)),
                ('accion_correctiva', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('verificacion', models.TextField(blank=True, null=True)),
                ('estado_verificacion', models.CharField(default='Pendiente de verificación', max_length=50)),
                ('mongo_doc_id', models.CharField(max_length=50)),
                ('db_origen', models.CharField(max_length=100)),
                ('coll_origen', models.CharField(max_length=100)),
                ('campo_cantidad_origen', models.CharField(default='Stock Actual', max_length=100)),
            ],
        ),
    ]
