# Generated by Django 6.0.2 on 2026-02-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_registrointegridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('modificación', 'Modificación'), ('eliminación', 'Eliminación'), ('solicitud', 'Solicitud'), ('registros', 'Registros'), ('creación', 'Creación'), ('importación', 'Importación')], max_length=50)),
                ('detalle_cambio', models.TextField()),
                ('usuario', models.CharField(max_length=150)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('base', models.CharField(default='-', max_length=100)),
                ('coleccion', models.CharField(default='-', max_length=100)),
                ('datos_extra', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
