# Generated by Django 6.0.2 on 2026-02-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_historialcambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Pendiente', '🟡 Pendiente'), ('Aprobada', '🟢 Aprobada'), ('Rechazada', '🔴 Rechazada'), ('Modificada', '🟠 Modificada'), ('Recepcionada', '✅ Recepcionada'), ('Cancelada', '⚫ Cancelada')], default='Pendiente', max_length=50),
        ),
    ]
